#!/usr/bin/env python3
# embed_ptx.py — wrap a PTX file into a C header as a NUL-terminated byte array.
# Part of the `lens` build (BUILD step 2): turns lens_device.ptx into
# lens_device_ptx.h so the OptiX module is embedded in a self-contained lens.exe.
# Deterministic; no third-party deps. Usage: python embed_ptx.py <in.ptx> <out.h>
import sys

def main():
    if len(sys.argv) != 3:
        sys.stderr.write("usage: embed_ptx.py <in.ptx> <out.h>\n")
        return 2
    with open(sys.argv[1], "rb") as f:
        data = f.read()
    n = len(data)
    out = []
    out.append("// generated by embed_ptx.py from %s — DO NOT EDIT\n" % sys.argv[1].replace("\\", "/"))
    out.append("#pragma once\n#include <cstddef>\n")
    out.append("static const unsigned char LENS_DEVICE_PTX[] = {\n")
    line = []
    for i, b in enumerate(data):
        line.append("0x%02x," % b)
        if len(line) == 20:
            out.append("  " + "".join(line) + "\n")
            line = []
    line.append("0x00")  # NUL terminator (excluded from the declared length)
    out.append("  " + "".join(line) + "\n};\n")
    out.append("static const size_t LENS_DEVICE_PTX_len = %d;\n" % n)
    with open(sys.argv[2], "w", newline="\n") as f:
        f.write("".join(out))
    return 0

if __name__ == "__main__":
    sys.exit(main())
